// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX4c5QpEjjRpAtG4L_ZxDFVvB7l6WaA4I',
    appId: '1:497829308678:web:6a372a2db230fe8a295687',
    messagingSenderId: '497829308678',
    projectId: 'eat-app-ef11a',
    authDomain: 'eat-app-ef11a.firebaseapp.com',
    storageBucket: 'eat-app-ef11a.appspot.com',
    measurementId: 'G-D93JJ82RRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKkaIaMGjerr0mEfocvnsOWWBctpNTho',
    appId: '1:497829308678:android:c2c700f76700e77e295687',
    messagingSenderId: '497829308678',
    projectId: 'eat-app-ef11a',
    storageBucket: 'eat-app-ef11a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGziEgwkHaEcUh1DNpsxxbnnvgm_DRRkM',
    appId: '1:497829308678:ios:21e4b8fa3f7349bf295687',
    messagingSenderId: '497829308678',
    projectId: 'eat-app-ef11a',
    storageBucket: 'eat-app-ef11a.appspot.com',
    iosClientId: '497829308678-79csh1ritf5uck654oh662qhun8u22cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatApp',
  );
}
